name: Install OpenSSH, Create Root User, and Start Chrome Remote Desktop

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install OpenSSH Server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
      shell: bash

    - name: Start OpenSSH Service
      run: |
        sudo systemctl start ssh
        sudo systemctl enable ssh
      shell: bash

    - name: Set Root Password
      run: |
        sudo echo 'root:28121998' | sudo chpasswd
      shell: bash

    - name: Download Chrome Remote Desktop Deb
      run: |
        curl -O https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
      shell: bash

    - name: Install Chrome Remote Desktop
      run: |
        sudo dpkg -i chrome-remote-desktop_current_amd64.deb
        sudo apt install --fix-broken -y
      shell: bash

    - name: Authenticate and Start Chrome Remote Desktop
      run: |
        sudo /opt/google/chrome-remote-desktop/chrome-remote-desktop --start
        sudo /opt/google/chrome-remote-desktop/chrome-remote-desktop --pin="${{ github.event.inputs.pincode }}"
        echo ${{ github.event.inputs.authcode }} | sudo /opt/google/chrome-remote-desktop/chrome-remote-desktop --remotely-connect
      shell: bash

    - name: Start Chrome Remote Desktop Host
      run: |
        DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0Adeu5BXan8HJXHcC_2EN_KQTSkxau7-FYM4FzppZY9K1nf2SlKZJ4vuhfmEo6wBL8hPHKw" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
      shell: bash

    - name: Keep Alive
      run: sleep 24h
      shell: bash
