name: Install OpenSSH, Create Root User, and Start Chrome Remote Desktop

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install OpenSSH Server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-server
      shell: bash

    - name: Start OpenSSH Service
      run: |
        sudo systemctl start ssh
        sudo systemctl enable ssh
      shell: bash

    - name: Set Root Password
      run: |
        sudo echo 'root:28121998' | sudo chpasswd
      shell: bash

       - name: Keep Alive
      run: sleep 24h
      shell: bash
